dist: trusty
sudo: false
addons:
  apt:
    packages:
      - google-chrome-stable
language: node_js
node_js:
  - "6"
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
install:
  - npm install -g @angular/cli
  - npm install
after_success:
  - npm run build
  - cd dist
  - zip dist.zip $(find . -mindepth 1 -not -iwholename "*.git*")
  - mv dist.zip ../
deploy:
  provider: releases
  api_key: $GITHUB_AUTH_TOKEN
  file: dist.zip
  skip_cleanup: true
  on:
    tags: true
